import{a as M,i as m,S as P}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const g=15;async function h(r,t){const i="https://pixabay.com/api/",a=new URLSearchParams({key:"44085737-801aedd726c9c1496368a8656",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:g});return(await M(`${i}?${a}`)).data}function $({webformatURL:r,largeImageURL:t,tags:i,likes:a,views:e,comments:o,downloads:n}){return`
        <li class="gallery-item">
          <a class="gallery-link" href="${t}">
            <img class="gallery-image" src="${r}" alt="${i}"/>
          </a>
          <ul class="info">
            <li class="info-item"> <b>Likes</b> ${a} </li>
            <li class="info-item"> <b>Views</b> ${e} </li>
            <li class="info-item"> <b>Comments</b> ${o} </li>
            <li class="info-item"> <b>Downloads</b> ${n} </li>
          </ul>
        </li>
    `}function b(r){return r.map($).join("")}const L=document.querySelector(".search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),p=document.querySelector(".load-more");let u="",d=0;L.addEventListener("submit",q);function q(r){if(r.preventDefault(),u=L.inputSearch.value.trim(),s(),!!u)return H(),c.innerHTML="",h(u,d=1).then(t=>{if(t.hits.length===0)return c.innerHTML="",s(),m.error({...y,...O});const i=b(t.hits);c.insertAdjacentHTML("afterbegin",i),w.refresh(),S(),t.hits.length>=t.totalHits&&s()}).catch(t=>{m.error({...y,message:t.message})}).finally(()=>{f()}),r.target.reset()}p.addEventListener("click",v);async function v(){s(),B();try{const r=await h(u,d+=1),t=b(r.hits);let i=d*g;c.insertAdjacentHTML("beforeend",t),w.refresh(),S(),i>=r.totalHits&&(s(),m.info({...y,...T}),f());const e=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({left:0,top:e,behavior:"smooth"})}catch(r){alert(r.message)}finally{f()}}function S(){p.style.display="block"}function s(){p.style.display="none"}function H(){l.style.position="absolute",l.style.display="inline-block"}function B(){l.style.position="relative",l.style.display="inline-block"}function f(){l.style.display="none"}const y={position:"topRight",timeout:1800,maxWidth:300,progressBar:!1},O={icon:"none",message:"Sorry, there are no images matching your search query. Please try again!"},T={message:"We are sorry, but you have reached the end of search results."};let w=new P(".gallery a",{captionDelay:250,captionsData:"alt"});
//# sourceMappingURL=commonHelpers.js.map
