import{a as M,i as g,S as P}from"./assets/vendor-c493984e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function y(t,a){const o="https://pixabay.com/api/",i=new URLSearchParams({key:"44085737-801aedd726c9c1496368a8656",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15});return(await M(`${o}?${i}`)).data}function v({webformatURL:t,largeImageURL:a,tags:o,likes:i,views:e,comments:r,downloads:s}){return`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${t}" alt="${o}"/>
          </a>
          <ul class="info">
            <li class="info-item"> <b>Likes</b> ${i} </li>
            <li class="info-item"> <b>Views</b> ${e} </li>
            <li class="info-item"> <b>Comments</b> ${r} </li>
            <li class="info-item"> <b>Downloads</b> ${s} </li>
          </ul>
        </li>
    `}function h(t){return t.map(v).join("")}const p=document.querySelector(".search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),f=document.querySelector(".load-more");let n="",u=0,m=0;p.addEventListener("input",t=>{n=t.target.value.trim()});p.addEventListener("submit",$);function $(t){return t.preventDefault(),N(),n?(localStorage.getItem("imageName")!==n&&(u=0),c.innerHTML="",y(n,u+=1).then(o=>{if(o.hits.length===0)return c.innerHTML="",L(),g.error({...S,...H});const i=h(o.hits);c.insertAdjacentHTML("afterbegin",i),w.refresh(),m=o.hits.length,b()}).catch(o=>console.log(o)).finally(()=>{d()}),localStorage.setItem("imageName",n),t.target.reset()):void 0}f.addEventListener("click",q);async function q(){L(),B();try{const t=await y(n,u+=1),a=h(t.hits);if(m+=t.hits.length,m>=t.totalHits)return g.info({...S,...I});c.insertAdjacentHTML("beforeend",a),w.refresh(),b();const i=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({left:0,top:i,behavior:"smooth"})}catch(t){alert(t.message)}finally{d()}}function b(){f.style.display="block"}function L(){f.style.display="none"}function N(){l.style.position="absolute",l.style.display="inline-block"}function B(){l.style.position="relative",l.style.display="inline-block"}function d(){l.style.display="none"}const S={position:"topRight",timeout:1800,maxWidth:300,progressBar:!1},H={icon:"none",message:"Sorry, there are no images matching your search query. Please try again!"},I={message:"We are sorry, but you have reached the end of search results."};let w=new P(".gallery a",{captionDelay:250,captionsData:"alt"});
//# sourceMappingURL=commonHelpers.js.map
